workflows:
  version: 2
  node-build:
    jobs:
      - node10
      - node12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run prettier:check
      - run: npm test

  node10:
    <<: *node-base
    docker:
      - image: node:20
  node12:
    <<: *node-base
    docker:
      - image: node:20
